defaults: &defaults
  CHANNEL_SECRET: d6c8e77cbc44f5c2778cd018e8eaf490
  CHANNEL_TOKEN: DU8P3ttHJVN2R9+gKfoq1CJ3z2mWesHAGRF5/ZP4ddU+txg85nbVV+A3qSmBGU4xYlW6z10aoZK3StQ6ow+FWyq6Sw0aqutHfQy4QT3YEdm1gVZbUp+bWIBjXnxIryx9y76sX/oG1HML/Et+OjHFcwdB04t89/1O/w1cDnyilFU=